### ISSUE TITLE
Jobs created from template don't copy over Build Triggers

### ISSUE THREAD

**Issue by trikosuave** [entagen/jenkins-build-per-branch#57]
I have my template set to build after the syncWithRepo job. After my first run and all the jobs for all the branches were created, only the master (template) built. I know there is a flag for it to start right away, but I them all to run after the main job runs so they can rebuild if the repo changes. Build Triggers are empty on the newly created jobs, so I have to run them manually every time which does not make for good automation. :)

Thanks!

**Comment by jamesdh** [comment]
Closing due to 1+ year of no response/info
