### ISSUE TITLE
Could not find method groovy() for arguments [org.codehaus.groovy:groovy-all:1.8.8] on root project

### ISSUE THREAD

**Issue by tknerr** [entagen/jenkins-build-per-branch#68]
Followed [your guide here](http://entagen.github.io/jenkins-build-per-branch/) but got this exception:

```
[workspace] $ /var/lib/jenkins/tools/hudson.plugins.gradle.GradleInstallation/Gradle_2.0/bin/gradle -DjenkinsUrl=http://localhost:8080/jenkins -DgitUrl=git+ssh://xxx@acme.org/home/xxx/git/repos/maven-dummy.git -DtemplateJobPrefix=MyDummy -DtemplateBranchName=master -DnestedView=MyDummy-branches -DdryRun=true syncWithRepo

FAILURE: Build failed with an exception.

* Where:
Build file '/data/jenkins/jobs/SyncDummyGitBranchesWithJenkins/workspace/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating root project 'workspace'.
> Could not find method groovy() for arguments [org.codehaus.groovy:groovy-all:1.8.8] on root project 'workspace'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.806 secs
Build step 'Invoke Gradle script' changed build result to FAILURE
Build step 'Invoke Gradle script' marked build as failure
Finished: FAILURE
```

This is using:
- Jenkins 1.572
- Gradle Plugin 1.24 (added Gradle 2.0 installation)
- GIT Plugin 2.2.4 
- jenkins-build-per-branch from master

Any ideas?

**Comment by tinyrye** [comment]
I had the same problem as you and went back to Gradle 1.8.  After doing so Gradle informed me this was unnecessary:

"The groovy configuration has been deprecated and is scheduled to be removed in Gradle 2.0. Typically, usages of 'groovy' can simply be replaced with 'compile'. In some cases, it may be necessary to additionally configure the 'groovyClasspath' property of GroovyCompile and Groovydoc tasks."

Running Gradle tasks were successful after changing 'groovy' dependency configs to 'compile'.  I tried with both the wrapper and the native install of gradle.

**Comment by mukeshkamboj** [comment]
@tinyrye 
I am new to gradle. There is below line in dependencies block in build.gradle file. 

groovy 'org.codehaus.groovy:groovy:2.2.1'

Why do we require this. This is breaking build with gradle 2.2.1 version. What is the use of it and alternative of it.

Please point me to the link where i can study this.

**Comment by mcordone** [comment]
I know this is a little bit old but getting same error using Gradle 2.3 or 2.7, is this issue has ever been address? any solution?

Thanks

**Comment by voidabhi** [comment]
+1

**Comment by jamesdh** [comment]
It's a legacy declaration for using groovy in Gradle 1.x. That's why it's good practice to include the gradle wrapper in gradle projects, and hence why it's suggested to use gradlew within this project while running it as opposed to your local host systems installation of gradle.
