### ISSUE TITLE
Server Error 500 issues with scalability?

### ISSUE THREAD

**Issue by sundaymtn** [entagen/jenkins-build-per-branch#69]
Hi,
Using https://github.com/entagen/jenkins-build-per-branch/commit/af18a93fecec115a9325175a644dfb596aa1895b I set up two master template jobs on Jenkins and 7 feature branches in the targeted git repo.  I set up a jenkins job to run the syncWithRepo and it gets through ~1-5 them and then throws a "HTTP/1.1 500 Server Error 500" which is logged as "Caused by: java.lang.IllegalStateException: Cannot create a session after the response has been committed" in catalina.out
If I repeatedly run the sync job it will eventually create all 14 jobs and add them to their respective views but it takes ~4-5 failed attempts to work through them.

I've seen the same behavior on two separate jenkins instances:
Jenkins ver. 1.554.2.2 (Jenkins Enterprise by CloudBees 14.05) on Jetty
Jenkins ver. 1.536 on Tomcat 6.0.35
Both running on CentOS 6.3 hosts

Console Output 
https://gist.github.com/sundaymtn/6cd7b04f51c5010a5fed#file-syncwithrepo_jenkinsoutput

Tomcat Output
https://gist.github.com/sundaymtn/4d80798d58b067b8b56f#file-catalina-out

**Comment by jamesdh** [comment]
@sundaymtn just out of curiosity, are the instances you speak of fronted by Apache?

**Comment by sundaymtn** [comment]
@jamesdh I don't have those environments anymore but there's a good chance they were proxied via apache httpd, I was also using nginx at the time too though.

**Comment by jamesdh** [comment]
Ok, thanks for the response! Without more info I'm closing this for now. Fairly certain this is a bug w/ the Jenkins instance rather than BPB.
