### ISSUE TITLE
Columns of a nested view are not created in Jenkins ver. 1.609.1

### ISSUE THREAD

**Issue by vinograt** [entagen/jenkins-build-per-branch#85]
Columns of a nested view are not created in Jenkins ver. 1.609.1

**Comment by jeichel-miovision** [comment]
confirmed on my machine as well

**Comment by vinograt** [comment]
Maybe I've inaccurately described my case. When a new branch is created in repository a set of nested views is created too. Unfortunately these views are not contain any columns as it were in the previous version of Jenkins. Columns can be added manually but it is inconvenient as you know.

**Comment by ruschecker** [comment]
I have the same issue

**Comment by ruschecker** [comment]
It may be linked with 
https://issues.jenkins-ci.org/browse/JENKINS-25403
