### ISSUE TITLE
Documentation page is down

### ISSUE THREAD

**Issue by QIvan** [entagen/jenkins-build-per-branch#94]
[Site with documentation](http://entagen.github.io/jenkins-build-per-branch/) gets 404 code.
***$ curl -I  http://entagen.github.io/jenkins-build-per-branch/***
HTTP/1.1 404 Not Found
Server: GitHub.com
Content-Type: text/html; charset=utf-8
ETag: "5519ee21-247c"
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
X-GitHub-Request-Id: 17EB2B1B:09B4:11FC3D54:56420479
Content-Length: 9340
Accept-Ranges: bytes
Date: Tue, 10 Nov 2015 14:51:38 GMT
Via: 1.1 varnish, 1.1 wcg-cluster.open.ru
Age: 74
X-Served-By: cache-ams4127-AMS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1447167098.384587,VS0,VE91
Vary: Accept-Encoding
X-Fastly-Request-ID: ac3b87c922fa999b352721d9c54309939282d2cd
 
And it is not just for me: http://downforeveryoneorjustme.com/http://entagen.github.io/jenkins-build-per-branch/

**Comment by sheehan** [comment]
Fixed now, thanks.

**Comment by QIvan** [comment]
Thank you a lot!
